spring.application.name=MediQueue
server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/mediqueue}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Ajay@123456}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:ThisIsMyVeryStrongSecretKeyForMediQueueProject2026@123456}
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=465

spring.mail.username=${MAIL_USERNAME:gundala.ajay4321@gmail.com}
spring.mail.password=${MAIL_PASSWORD:wllkbiakdwrepokv}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000